<!DOCTYPE html>
<html>
	<head data-gwd-animation-mode="quickMode">
		<meta charset="utf-8">
		<meta name="GCD" content="YTk3ODQ3ZWZhN2I4NzZmMzBkNTEwYjJlfc54af80aa4706c276506c085d97db3d"/>
    <meta name="generator" content="Google Web Designer 1.0.1.1025">
    <meta name="template" content="Banner 1.0.5">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>FuelPHP Framework</title>
		<?php echo Asset::css('bootstrap.css'); ?>
		<?php echo Asset::css('header.css'); ?>
		<?php echo Asset::css('swipe.css'); ?>
		<?php echo Asset::css('tenkey.css'); ?>
		<script type="text/javascript" src="http://s0.2mdn.net/ads/studio/Enabler.js"></script><script type="text/javascript" data-exports-type="rad.ad.RichMedia">// Copyright 2013 Google Inc. All Rights Reserved.
(function(){var e,k=this,m=function(a,b,c){a=a.split(".");c=c||k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]?c[d]:c[d]={}:c[d]=b},aa=function(){},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},n=function(a){return"array"==ba(a)},p=function(a){return"string"==typeof a},ea=function(a){return a[ca]||(a[ca]=++da)},ca="closure_uid_"+(1E9*Math.random()>>>0),da=0,fa=function(a,b,c){return a.call.apply(a.bind,
arguments)},ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return q.apply(null,arguments)},ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=
c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ia=Date.now||function(){return+new Date},s=function(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return q.apply(null,c)}return q(this,a)};var ja=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ka=function(a){return Array.prototype.join.call(arguments,"")},la=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})},ma=function(a){var b=p(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};var na,u=function(){return k.navigator?k.navigator.userAgent:""},oa=-1!=u().indexOf("Android"),pa=-1!=u().indexOf("MSIE");var v,qa,ra,sa,ta=function(){return k.navigator?k.navigator.userAgent:null};sa=ra=qa=v=!1;var ua;if(ua=ta()){var va=k.navigator;v=0==ua.lastIndexOf("Opera",0);qa=!v&&(-1!=ua.indexOf("MSIE")||-1!=ua.indexOf("Trident"));ra=!v&&-1!=ua.indexOf("WebKit");sa=!v&&!ra&&!qa&&"Gecko"==va.product}var wa=v,w=qa,x=sa,xa=ra,ya=function(){var a=k.document;return a?a.documentMode:void 0},za;
i:{var Aa="",Ba;if(wa&&k.opera)var Ca=k.opera.version,Aa="function"==typeof Ca?Ca():Ca;else if(x?Ba=/rv\:([^\);]+)(\)|;)/:w?Ba=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:xa&&(Ba=/WebKit\/(\S+)/),Ba)var Da=Ba.exec(ta()),Aa=Da?Da[1]:"";if(w){var Ea=ya();if(Ea>parseFloat(Aa)){za=String(Ea);break i}}za=Aa}
var Fa=za,Ga={},y=function(a){var b;if(!(b=Ga[a])){b=0;for(var c=ja(String(Fa)).split("."),d=ja(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var h=c[g]||"",l=d[g]||"",r=RegExp("(\\d*)(\\D*)","g"),L=RegExp("(\\d*)(\\D*)","g");do{var B=r.exec(h)||["","",""],t=L.exec(l)||["","",""];if(0==B[0].length&&0==t[0].length)break;b=((0==B[1].length?0:parseInt(B[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==B[1].length?0:parseInt(B[1],10))>(0==t[1].length?0:parseInt(t[1],10))?1:
0)||((0==B[2].length)<(0==t[2].length)?-1:(0==B[2].length)>(0==t[2].length)?1:0)||(B[2]<t[2]?-1:B[2]>t[2]?1:0)}while(0==b)}b=Ga[a]=0<=b}return b},Ha=k.document,Ia=Ha&&w?ya()||("CSS1Compat"==Ha.compatMode?parseInt(Fa,10):5):void 0;var Ja=function(){if(!oa)return 0;if(void 0===na){var a=/Android\s+([0-9.]+)/.exec(u());na=a&&2==a.length?a[1]:""}return parseInt(na,10)||0},Ka=function(){return wa?"-o-":w?"":x?"-moz-":"-webkit-"};var z=Array.prototype,La=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ma=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=p(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Na=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,h=p(a)?
a.split(""):a,l=0;l<d;l++)if(l in h){var r=h[l];b.call(c,r,l,a)&&(f[g++]=r)}return f},Oa=function(a,b){return 0<=La(a,b)},Pa=function(a,b){var c=La(a,b),d;(d=0<=c)&&z.splice.call(a,c,1);return d},Qa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ra=function(a,b){return Na(a,function(a){return!Oa(b,a)})},Sa=function(a,b){var c=document.body,d;d=c.className;d=p(d)&&d.match(/\S+/g)||[];p(a)?Pa(d,a):n(a)&&(d=Ra(d,a));if(p(b)&&!Oa(d,b))d.push(b);else if(n(b))for(var f=d,g=0;g<b.length;g++)Oa(f,b[g])||f.push(b[g]);d=d.join(" ");c.className=d};var A=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ta=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Ua=function(a,b){b in a&&delete a[b]},Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Wa=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Va.length;g++)c=Va[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};!x&&!w||w&&w&&9<=Ia||x&&y("1.9.1");w&&y("9");var Xa=function(a,b){a.appendChild(b)},Ya=function(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};var C=function(){};C.prototype.Ea=!1;C.prototype.isDisposed=function(){return this.Ea};C.prototype.dispose=function(){this.Ea||(this.Ea=!0,this.b())};var Za=function(a,b){a.V||(a.V=[]);a.V.push(q(b,void 0))};C.prototype.b=function(){if(this.V)for(;this.V.length;)this.V.shift()()};var $a=function(a){a&&"function"==typeof a.dispose&&a.dispose()};var D=function(a,b){this.type=a;this.currentTarget=this.target=b};e=D.prototype;e.b=function(){};e.dispose=function(){};e.w=!1;e.defaultPrevented=!1;e.Ya=!0;e.stopPropagation=function(){this.w=!0};e.preventDefault=function(){this.defaultPrevented=!0;this.Ya=!1};var ab=function(a){a.preventDefault()};var bb=function(a){bb[" "](a);return a};bb[" "]=aa;var cb=!w||w&&9<=Ia,db=w&&!y("9");!xa||y("528");x&&y("1.9b")||w&&y("8")||wa&&y("9.5")||xa&&y("528");x&&!y("8")||w&&y("9");var eb=function(a,b){a&&this.init(a,b)};s(eb,D);e=eb.prototype;e.target=null;e.relatedTarget=null;e.offsetX=0;e.offsetY=0;e.clientX=0;e.clientY=0;e.screenX=0;e.screenY=0;e.button=0;e.keyCode=0;e.charCode=0;e.ctrlKey=!1;e.altKey=!1;e.shiftKey=!1;e.metaKey=!1;e.o=null;
e.init=function(a,b){var c=this.type=a.type;D.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(x){var f;i:{try{bb(d.nodeName);f=!0;break i}catch(g){}f=!1}f||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=xa||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=xa||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.o=a;a.defaultPrevented&&this.preventDefault();delete this.w};e.stopPropagation=function(){eb.a.stopPropagation.call(this);this.o.stopPropagation?this.o.stopPropagation():this.o.cancelBubble=!0};
e.preventDefault=function(){eb.a.preventDefault.call(this);var a=this.o;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,db)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};e.b=function(){};var fb="closure_listenable_"+(1E6*Math.random()|0),E=function(a){try{return!(!a||!a[fb])}catch(b){return!1}},gb=0;var hb=function(a,b,c,d,f){this.C=a;this.ea=null;this.src=b;this.type=c;this.capture=!!d;this.n=f;this.key=++gb;this.G=this.ba=!1},ib=function(a){a.G=!0;a.C=null;a.ea=null;a.src=null;a.n=null};var F=function(a){this.src=a;this.f={};this.M=0};F.prototype.add=function(a,b,c,d,f){var g=this.f[a];g||(g=this.f[a]=[],this.M++);var h=jb(g,b,d,f);-1<h?(a=g[h],c||(a.ba=!1)):(a=new hb(b,this.src,a,!!d,f),a.ba=c,g.push(a));return a};F.prototype.remove=function(a,b,c,d){if(!(a in this.f))return!1;var f=this.f[a];b=jb(f,b,c,d);return-1<b?(ib(f[b]),z.splice.call(f,b,1),0==f.length&&(delete this.f[a],this.M--),!0):!1};
var kb=function(a,b){var c=b.type;if(!(c in a.f))return!1;var d=Pa(a.f[c],b);d&&(ib(b),0==a.f[c].length&&(delete a.f[c],a.M--));return d};F.prototype.removeAll=function(a){var b=0,c;for(c in this.f)if(!a||c==a){for(var d=this.f[c],f=0;f<d.length;f++)++b,ib(d[f]);delete this.f[c];this.M--}return b};F.prototype.da=function(a,b){var c=this.f[a],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.capture==b&&d.push(g)}return d};
F.prototype.O=function(a,b,c,d){a=this.f[a];var f=-1;a&&(f=jb(a,b,c,d));return-1<f?a[f]:null};var jb=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.G&&g.C==b&&g.capture==!!c&&g.n==d)return f}return-1};var lb="closure_lm_"+(1E6*Math.random()|0),mb={},nb=0,ob=function(a,b,c,d,f){if(n(b)){for(var g=0;g<b.length;g++)ob(a,b[g],c,d,f);return null}c=pb(c);return E(a)?a.l(b,c,d,f):qb(a,b,c,!1,d,f)},qb=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var h=!!f,l=G(a);l||(a[lb]=l=new F(a));c=l.add(b,c,d,f,g);if(c.ea)return c;d=rb();c.ea=d;d.src=a;d.C=c;a.addEventListener?a.addEventListener(b,d,h):a.attachEvent(b in mb?mb[b]:mb[b]="on"+b,d);nb++;return c},rb=function(){var a=sb,b=cb?function(c){return a.call(b.src,
b.C,c)}:function(c){c=a.call(b.src,b.C,c);if(!c)return c};return b},H=function(a,b,c,d,f){if(n(b)){for(var g=0;g<b.length;g++)H(a,b[g],c,d,f);return null}c=pb(c);return E(a)?a.k(b,c,d,f):qb(a,b,c,!0,d,f)},tb=function(a,b,c,d,f){if(n(b))for(var g=0;g<b.length;g++)tb(a,b[g],c,d,f);else c=pb(c),E(a)?a.D(b,c,d,f):a&&(a=G(a))&&(b=a.O(b,c,!!d,f))&&ub(b)},ub=function(a){if("number"==typeof a||!a||a.G)return!1;var b=a.src;if(E(b))return kb(b.q,a);var c=a.type,d=a.ea;b.removeEventListener?b.removeEventListener(c,
d,a.capture):b.detachEvent&&b.detachEvent(c in mb?mb[c]:mb[c]="on"+c,d);nb--;(c=G(b))?(kb(c,a),0==c.M&&(c.src=null,b[lb]=null)):ib(a);return!0},wb=function(a,b,c,d){var f=1;if(a=G(a))if(b=a.f[b])for(b=Qa(b),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.G&&(f&=!1!==vb(g,d))}return Boolean(f)},vb=function(a,b){var c=a.C,d=a.n||a.src;a.ba&&ub(a);return c.call(d,b)},sb=function(a,b){if(a.G)return!0;if(!cb){var c;if(!(c=b))i:{c=["window","event"];for(var d=k,f;f=c.shift();)if(null!=d[f])d=d[f];else{c=
null;break i}c=d}f=c;c=new eb(f,this);d=!0;if(!(0>f.keyCode||void 0!=f.returnValue)){i:{var g=!1;if(0==f.keyCode)try{f.keyCode=-1;break i}catch(h){g=!0}if(g||void 0==f.returnValue)f.returnValue=!0}f=[];for(g=c.currentTarget;g;g=g.parentNode)f.push(g);for(var g=a.type,l=f.length-1;!c.w&&0<=l;l--)c.currentTarget=f[l],d&=wb(f[l],g,!0,c);for(l=0;!c.w&&l<f.length;l++)c.currentTarget=f[l],d&=wb(f[l],g,!1,c)}return d}return vb(a,new eb(b,this))},G=function(a){a=a[lb];return a instanceof F?a:null},xb="__closure_events_fn_"+
(1E9*Math.random()>>>0),pb=function(a){return"function"==ba(a)?a:a[xb]||(a[xb]=function(b){return a.handleEvent(b)})};var I=function(){this.q=new F(this);this.Rb=this};s(I,C);I.prototype[fb]=!0;e=I.prototype;e.aa=null;e.gc=function(a){this.aa=a};e.addEventListener=function(a,b,c,d){ob(this,a,b,c,d)};e.removeEventListener=function(a,b,c,d){tb(this,a,b,c,d)};
e.dispatchEvent=function(a){var b,c=this.aa;if(c)for(b=[];c;c=c.aa)b.push(c);var c=this.Rb,d=a.type||a;if(p(a))a=new D(a,c);else if(a instanceof D)a.target=a.target||c;else{var f=a;a=new D(d,c);Wa(a,f)}var f=!0,g;if(b)for(var h=b.length-1;!a.w&&0<=h;h--)g=a.currentTarget=b[h],f=yb(g,d,!0,a)&&f;a.w||(g=a.currentTarget=c,f=yb(g,d,!0,a)&&f,a.w||(f=yb(g,d,!1,a)&&f));if(b)for(h=0;!a.w&&h<b.length;h++)g=a.currentTarget=b[h],f=yb(g,d,!1,a)&&f;return f};
e.b=function(){I.a.b.call(this);this.removeAllListeners();this.aa=null};e.l=function(a,b,c,d){return this.q.add(String(a),b,!1,c,d)};e.k=function(a,b,c,d){return this.q.add(String(a),b,!0,c,d)};e.D=function(a,b,c,d){return this.q.remove(String(a),b,c,d)};e.removeAllListeners=function(a){return this.q?this.q.removeAll(a):0};
var yb=function(a,b,c,d){b=a.q.f[String(b)];if(!b)return!0;b=Qa(b);for(var f=!0,g=0;g<b.length;++g){var h=b[g];if(h&&!h.G&&h.capture==c){var l=h.C,r=h.n||h.src;h.ba&&kb(a.q,h);f=!1!==l.call(r,d)&&f}}return f&&!1!=d.Ya};I.prototype.da=function(a,b){return this.q.da(String(a),b)};I.prototype.O=function(a,b,c,d){return this.q.O(String(a),b,c,d)};var J=function(a){I.call(this);this.mb=a.cssClass;this.Ub=a.elementCount;this.Ja=0};s(J,I);var zb=-1!=u().indexOf("WebKit")?"webkitAnimationEnd":"animationend";J.prototype.start=function(){this.dispatchEvent("animationstart");this.Ja=this.Ub;ob(document.body,zb,this.ha,!0,this);Sa(null,this.mb)};J.prototype.stop=function(){this.Fa();Ab(this)};J.prototype.Fa=function(){Sa(this.mb,null)};var Ab=function(a){tb(document.body,zb,a.ha,!0,a);a.dispatchEvent("animationend")};
J.prototype.ha=function(){this.Ja--;0>=this.Ja&&Ab(this)};m("rad.animation.CSSAnimation",J,void 0);var K=J.prototype;K.addEventListener=K.addEventListener;K.removeEventListener=K.removeEventListener;K.start=K.start;K.stop=K.stop;var Bb=function(a,b,c){if(n(b))for(var d=0;d<b.length;d++)Bb(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",encodeURIComponent(String(b)))},Cb=/#|$/,Db=function(a,b){var c=a.search(Cb),d;i:{d=0;for(var f=b.length;0<=(d=a.indexOf(b,d))&&d<c;){var g=a.charCodeAt(d-1);if(38==g||63==g)if(g=a.charCodeAt(d+f),!g||61==g||38==g||35==g)break i;d+=f+1}d=-1}if(0>d)return null;f=a.indexOf("&",d);if(0>f||f>c)f=c;d+=b.length+1;return decodeURIComponent(a.substr(d,f-d).replace(/\+/g," "))};Db(window.location.href,"canvasLogLevel");var Eb=function(){I.call(this);this.T=[];this.sb=0};s(Eb,I);var Fb=["abort","error","load"];Eb.prototype.add=function(a){if("string"==typeof a)this.T.push(a);else for(var b in a)this.T.push(a[b])};Eb.prototype.start=function(){Gb(this);for(var a in this.T){var b=this.T[a],c=document.createElement("img");H(c,Fb,this.Zb,void 0,this);c.src=b}};Eb.prototype.Zb=function(){this.sb++;this.dispatchEvent("progress");Gb(this)};var Gb=function(a){a.sb==a.T.length&&a.dispatchEvent("complete")};var Hb=function(){Eb.call(this)};s(Hb,Eb);var M=function(){this.ob=this.pb=this.qb=""},Ib={jc:"translate",hc:"rotate",ic:"scale"},Jb=function(){switch(Ka()){case "-moz-":return"MozTransform";case "-webkit-":return"webkitTransform";case "-o-":return"OTransform";default:return"transform"}}(),Kb=Ka()+"transform",Lb=function(){return Oa([1,2,3],Ja())?!1:"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix("")};
M.prototype.translate=function(a,b,c){var d="translate";a=[a,b];Lb()&&(d+="3d",p(c)?a.push(c):a.push("0px"));this.qb=d+"("+a.join(",")+")";return this};M.prototype.scale=function(a,b,c){b=p(b)?b:a;var d="scale";a=[a,b];Lb()&&(d+="3d",p(c)?a.push(c):a.push("1"));this.pb=d+"("+a.join(",")+")";return this};M.prototype.rotate=function(a){this.ob="rotate("+a+")";return this};M.prototype.I=function(){var a=ja([this.qb,this.pb,this.ob].join(" "));if(""===a)return{};var b={};b.transform=a;return b};var N=function(a){this.d=a;this.N={}};s(N,C);var Mb=[];e=N.prototype;e.l=function(a,b,c,d,f){n(b)||(Mb[0]=b,b=Mb);for(var g=0;g<b.length;g++){var h=ob(a,b[g],c||this.handleEvent,d||!1,f||this.d||this);if(!h)break;this.N[h.key]=h}return this};e.k=function(a,b,c,d,f){i:{if(n(b))for(var g=0;g<b.length;g++)this.k(a,b[g],c,d,f);else{a=H(a,b,c||this.handleEvent,d,f||this.d||this);if(!a){a=this;break i}this.N[a.key]=a}a=this}return a};
e.D=function(a,b,c,d,f){if(n(b))for(var g=0;g<b.length;g++)this.D(a,b[g],c,d,f);else c=c||this.handleEvent,f=f||this.d||this,c=pb(c),d=!!d,b=E(a)?a.O(b,c,d,f):a?(a=G(a))?a.O(b,c,d,f):null:null,b&&(ub(b),delete this.N[b.key]);return this};e.removeAll=function(){A(this.N,ub);this.N={}};e.b=function(){N.a.b.call(this);this.removeAll()};e.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Ob=function(a,b,c){p(b)?Nb(a,c,b):A(b,ha(Nb,a))},Nb=function(a,b,c){var d;i:if(d=la(c),void 0===a.style[d]&&(c=(xa?"Webkit":x?"Moz":w?"ms":wa?"O":null)+ma(c),void 0!==a.style[c])){d=c;break i}d&&(a.style[d]=b)};var O=function(a,b){I.call(this);this.h=a;this.h.id||(this.h.id=ea(this).toString());this.$a=b};s(O,I);e=O.prototype;e.$=!1;e.vb=!1;e.u=!1;e.getConfig=function(){var a=this.h,b={},c;for(c in a)b[c]=a[c];return b};e.setConfig=function(a){Wa(this.h,a);Pb(this)};e.getElement=function(){return this.A};e.setElement=function(a){this.A=a;Pb(this)};var Pb=function(a){a.getElement();a.getConfig();a.dispatchEvent("configured")};e=O.prototype;e.g=function(){this.d||(this.d=new N(this));return this.d};
e.L=function(){this.vb=!0;this.dispatchEvent("load")};e.isLoaded=function(){return this.vb};e.isBound=function(){return this.$};e.isVisible=function(){return this.u};e.load=function(){this.Ma()};e.Ma=function(){this.L()};e.createDom=function(){var a=document.createElement("DIV");this.setElement(a)};e.bind=function(){this.$=!0};e.present=function(){this.setVisible()};e.setVisible=function(){this.u=!0;this.dispatchEvent("visible")};e.dismiss=function(){this.u=!1;this.dispatchEvent("hidden")};
e.unbind=function(){this.d&&(this.d.dispose(),this.d=null);this.$=!1};e.b=function(){this.$&&this.unbind();delete this.A;O.a.b.call(this)};var Qb=function(a,b){O.call(this,a,b)};s(Qb,O);Qb.prototype.Ma=function(){var a=this.$a.getEnvironment().getFilename(this.getConfig().src),b=new Hb;b.add(a);this.g().k(b,"complete",this.Mb);b.start()};Qb.prototype.createDom=function(){var a=document.createElement("IMG");this.setElement(a)};Qb.prototype.Mb=function(){var a=this.$a.getEnvironment().getFilename(this.getConfig().src);this.getElement().setAttribute("src",a);this.L()};var Rb=function(a){a.addEventListener=a.addEventListener;a.removeEventListener=a.removeEventListener;a.getElement=a.getElement;a.setElement=a.setElement;a.getConfig=a.getConfig;a.setConfig=a.setConfig;a.createDom=a.createDom;a.load=a.load;a.bind=a.bind;a.present=a.present;a.dismiss=a.dismiss;a.unbind=a.unbind;a.dispose=a.dispose;a.isDisposed=a.isDisposed;a.isLoaded=a.isLoaded;a.isBound=a.isBound;a.isVisible=a.isVisible;a=D.prototype;m("goog.events.Event",D,void 0);a.stopPropagation=a.stopPropagation;
a.preventDefault=a.preventDefault;a.currentTarget=a.currentTarget;a.target=a.target;a.type=a.type};m("rad.ui.Image",Qb,void 0);Rb(Qb.prototype);var P=function(a,b){O.call(this,a,b)};s(P,O);P.prototype.La=function(a,b){var c=isNaN(b)?1:b;this.i||(this.i=[]);this.i[c]||(this.i[c]=[]);this.i[c].push(a);this.g().l(a,"configured",this.Fb)};P.prototype.Fb=function(){this.isLoaded()&&this.isVisible()&&Sb(this)};P.prototype.Ma=function(){Tb(this,0)};
var Tb=function(a,b){var c=0,d=q(function(a){a.target.removeEventListener("load",d,!1);c--;0==c&&Tb(this,b+1)},a);if(a.i&&a.i.length>b){var f=a.i[b];if(n(f)&&0<f.length)for(var c=f.length,g=0;g<f.length;g++)f[g].addEventListener("load",d,!1),f[g].load();else Tb(a,b+1)}else a.L()},Vb=function(a,b){if(n(a.i))for(var c=0;c<a.i.length;c++)Ub(a,b,c)},Ub=function(a,b,c){n(a.i)&&(c=a.i[c],n(c)&&Ma(c,b,a))};P.prototype.bind=function(){P.a.bind.call(this);Vb(this,function(a){this.appendChild(a);a.bind()})};
P.prototype.appendChild=function(a){var b=this.getElement();Ya(a.getElement(),function(a){return a==b})||Xa(b,a.getElement())};P.prototype.present=function(){n(this.i)?Sb(this):P.a.present.call(this)};var Sb=function(a){var b=0,c=0,d=q(function(a){a.target.removeEventListener("visible",d,!1);a.stopPropagation();c++;b==c&&this.setVisible()},a);Vb(a,function(a){b++;a.addEventListener("visible",d,!1);a.present()})};P.prototype.dismiss=function(){n(this.i)?Wb(this):P.a.dismiss.call(this)};
var Wb=function(a){var b=0,c=0,d=q(function(a){a.target.removeEventListener("hidden",d,!1);a.stopPropagation();c++;b==c&&(this.u=!1,this.dispatchEvent("hidden"))},a);Vb(a,function(a){b++;a.addEventListener("hidden",d,!1);a.dismiss()})};P.prototype.unbind=function(){Vb(this,function(a){a.unbind()});P.a.unbind.call(this)};P.prototype.b=function(){Vb(this,function(a){a.dispose()});this.i=null;P.a.b.call(this)};var Q=function(a,b){O.call(this,a,b);this.H=[]};s(Q,P);Q.prototype.Ba=function(a,b,c){this.H.push({src:a,type:b,n:c,Za:!1})};Q.prototype.bind=function(){for(var a=0;a<this.H.length;a++){var b=this.H[a];b.src.addEventListener(b.type,b.n,b.Za)}Q.a.bind.call(this)};Q.prototype.unbind=function(){for(var a=0;a<this.H.length;a++){var b=this.H[a];b.src.removeEventListener(b.type,b.n,b.Za)}Q.a.unbind.call(this)};Q.prototype.b=function(){this.H=null;Q.a.b.call(this)};var R=function(a,b){Q.call(this,a,b)};s(R,Q);e=R.prototype;e.tb=!1;e.jb=null;e.eb=null;e.fb=null;e.setElement=function(a){R.a.setElement.call(this,a);this.jb=this.getElement().parentElement};var Yb=function(a){a.tb||(a.tb=!0,a.dispatchEvent("brandingload"),Ub(a,function(a){this.appendChild(a)},0),Xb(a))},Xb=function(a){var b=a.jb||document.body;b!=a.getElement().parentElement&&(a=a.getElement(),b.appendChild(a))};e=R.prototype;e.Xa=function(){this.dispatchEvent("pagepresented")};
e.Ba=function(a,b,c){"pagepresented"==b||"pagepresenting"==b?a=this:"rotatetolandscape"==b?this.eb=c:"rotatetoportrait"==b&&(this.fb=c);R.a.Ba.call(this,a,b,c)};e.L=function(){Yb(this);R.a.L.call(this)};e.bind=function(){Xb(this);R.a.bind.call(this)};e.unbind=function(){R.a.unbind.call(this);var a=this.getElement();a&&a.parentNode&&a.parentNode.removeChild(a);(a=this.getConfig().introAnimationSequence)&&void 0!==a.Fa&&a.Fa()};
e.present=function(){R.a.present.call(this);this.dispatchEvent("pagepresenting");var a=this.getConfig().introAnimationSequence;a?(this.g().k(a,"animationend",this.Xa),a.start()):this.Xa()};e.dismiss=function(){R.a.dismiss.call(this)};e.b=function(){var a=this.getConfig();a.introAnimationSequence&&(a.introAnimationSequence.dispose&&a.introAnimationSequence.dispose(),a.introAnimationSequence=null);R.a.b.call(this)};m("rad.ui.Page",R,void 0);Rb(R.prototype);R.prototype.addChild=R.prototype.La;R.prototype.addEvent=R.prototype.Ba;var Zb=function(a,b){I.call(this);this.ga=a||1;this.F=b||k;this.Ca=q(this.Sb,this);this.Da=ia()};s(Zb,I);e=Zb.prototype;e.enabled=!1;e.r=null;e.Sb=function(){if(this.enabled){var a=ia()-this.Da;0<a&&a<0.8*this.ga?this.r=this.F.setTimeout(this.Ca,this.ga-a):(this.r&&(this.F.clearTimeout(this.r),this.r=null),this.dispatchEvent("tick"),this.enabled&&(this.r=this.F.setTimeout(this.Ca,this.ga),this.Da=ia()))}};
e.start=function(){this.enabled=!0;this.r||(this.r=this.F.setTimeout(this.Ca,this.ga),this.Da=ia())};e.stop=function(){this.enabled=!1;this.r&&(this.F.clearTimeout(this.r),this.r=null)};e.b=function(){Zb.a.b.call(this);this.stop();delete this.F};var $b=function(a,b,c){if("function"==ba(a))c&&(a=q(a,c));else if(a&&"function"==typeof a.handleEvent)a=q(a.handleEvent,a);else throw Error("Invalid listener argument");2147483647<b||k.setTimeout(a,b||0)};var ac=function(a,b){O.call(this,a,b);this.ua=this.ta=0;this.S=[]};s(ac,O);e=ac.prototype;e.bind=function(){ac.a.bind.call(this);this.getElement().style.cursor="pointer";this.g().l(this.getElement(),"click",this.oa);this.g().l(this.getElement(),"touchstart",this.Ab);this.g().l(document,"click",this.zb,!0)};e.Ab=function(a){a.stopPropagation();this.g().l(this.getElement(),"touchend",this.oa);this.g().l(document.body,"touchmove",this.Wa);this.ta=a.o.touches[0].clientX;this.ua=a.o.touches[0].clientY};
e.Wa=function(a){var b=a.o.touches[0].clientY;(10<Math.abs(a.o.touches[0].clientX-this.ta)||10<Math.abs(b-this.ua))&&this.fa()};e.oa=function(a){a.stopPropagation();this.fa();this.dispatchEvent("action");"touchend"==a.type&&(this.S.push(this.ta,this.ua),$b(q(this.Tb,this),2500))};e.Tb=function(){this.S.splice(0,2)};e.zb=function(a){for(var b=0;b<this.S.length;b+=2){var c=this.S[b+1];25>Math.abs(a.clientX-this.S[b])&&25>Math.abs(a.clientY-c)&&(a.stopPropagation(),a.preventDefault())}};
e.fa=function(){this.g().D(this.getElement(),"touchend",this.oa);this.g().D(document.body,"touchmove",this.Wa)};m("rad.ui.TapArea",ac,void 0);Rb(ac.prototype);var bc=function(){this.p={}};s(bc,C);bc.prototype.add=function(a,b,c){this.p[a]={from:b,R:c}};var cc=function(a,b){A(b.p,function(a,b){this.p[b]=a},a)},dc=function(a,b){var c={},d,f,g,h=b.replace(/ /g,"").split(")").slice(0,-1);Ma(h,function(a){d=a.split("(")[0];f=a.split("(")[1];"rotate3d"===d&&(f=f.split(",")[f.split(",").length-1]);g={};g.from=f;g.R=f;c[d.replace("3d","")]=g},a);A(c,function(a,b){var c=this.p;b in c||(c[b]=a)},a)};
bc.prototype.I=function(a){var b=Oa([1,2],Ja()),c={},d=new M,f=new M,g={},h={};this.p.transform&&(Ua(this.p,"rotate"),Ua(this.p,"translate"),Ua(this.p,"scale"));A(this.p,function(l,r){if("translate"===r){var L=l.from.split(","),B=l.R.split(",");d.translate.apply(d,L);f.translate.apply(f,B)}else"rotate"===r?(d.rotate(l.from),f.rotate(l.R)):"scale"===r?(L=l.from.split(","),B=l.R.split(","),d.scale.apply(d,L),f.scale.apply(f,B)):(g[r]=l.from,h[r]=l.R);if(b){var L=a+"_"+r,t;i:{for(t in Ib)if(Ib[t]==r){t=
!0;break i}t=!1}t?(t=[d.I(),f.I()],c[L]=t,d=new M,f=new M):(t=[g,h],c[L]=t,g={},h={})}},this);b||(Wa(g,d.I()),Wa(h,f.I()),c[a]=[g,h]);return c};bc.prototype.b=function(){delete this.p;bc.a.b.call(this)};var S=function(a){I.call(this);this.h=a;this.A=a.element||null;this.Qa=a.duration||"1s";this.qa=a.Cb||"0s";this.yb=a.easing||"ease";this.Sa=a.Db||1;this.W={};this.B=new bc;this.B.add(a.propertyName,a.K,a.J)};s(S,I);var ec=Ka(),fc=(-1!=u().indexOf("WebKit")?ec:"")+"animation",gc="@"+ec+"keyframes",hc=ec+"animation-fill-mode",ic=-1!=u().indexOf("WebKit")?"webkitAnimationEnd":"animationend";e=S.prototype;e.getConfig=function(){return this.h};
e.ka=function(){this.dispatchEvent("animationstart");var a=this.A,b=a.style[Jb];void 0!==b&&""!==b&&dc(this.B,b);b=this.h.id;b||(b=ea(this),this.h.id=b);b="anim_"+b+"_"+ea(a);b=this.B.I(b);"0s"===this.Qa?(Ob(a,fc,""),A(b,function(a){Wa(this.W,a[1])},this),$b(this.ab,1E3*parseFloat(this.qa.substr(0,this.qa.length-1)),this)):(H(a,ic,this.ab,!1,this),A(b,function(a,b){var f=b+"-animation-script",g=document;if(p(f)?!g.getElementById(f):!f){for(var g=gc+" "+b+" {",h=0;h<a.length;h++){var l=Math.round(100*
Math.abs(h/(a.length-1))),g=g+(l+"% {"),r;for(r in a[h])g="transform"===r?g+(Kb+":"+a[h][r]+";"):g+(r+":"+a[h][r]+";");g+="}"}g+="}";r=document.createElement("style");r.id=f;r.innerHTML=g;document.getElementsByTagName("head")[0].appendChild(r)}Wa(this.W,a[1])},this),Ob(a,jc(this,Ta(b))))};e.start=function(){this.ka()};e.stop=function(){};e.ab=function(){Ob(this.A,this.W);this.dispatchEvent("animationend")};
var jc=function(a,b){var c={};c[fc]="";var d=c[hc]="";A(b,function(a){c[fc]+=d+[a,this.Qa,this.yb,this.qa,-1===this.Sa?"infinite":this.Sa].join(" ");c[hc]+=d+"both";d=", "},a);return c};S.prototype.b=function(){delete this.h;this.W=this.A=null;this.B.dispose();delete this.B;S.a.b.call(this)};var kc=function(){I.call(this);this.Q={};this.ja=0};s(kc,I);e=kc.prototype;e.add=function(a){var b=ea(a.A),c=this.Q,d=0,f;for(f in c)d++;0!==d&&void 0!==this.Q[b]?cc(this.Q[b].B,a.B):this.Q[b]=a;return this};e.ka=function(){this.dispatchEvent("animationstart");this.ja=0;A(this.Q,function(a){this.ja++;H(a,"animationend",this.ha,!1,this);a.ka()},this)};e.start=function(){this.ka()};e.stop=function(){};e.ha=function(){this.ja--;0>=this.ja&&this.dispatchEvent("animationend")};var lc=function(){};e=lc.prototype;e.id=NaN;e.propertyName="";e.K="";e.J="";e.duration="";e.Cb="";e.easing="ease";e.Db=1;e.element=null;e.setElement=function(a){this.element=a};var T=function(a,b,c){I.call(this);this.m=a;this.t=b;this.type=c.type||"none";this.duration=c.duration||0;this.easing=c.easing||"ease";this.direction=c.direction||"right";this.n=new N(this)};s(T,I);T.prototype.pa=aa;T.prototype.va=function(){this.m&&(this.m.style[fc]="none",this.m.style[Jb]="none")};T.prototype.start=function(){this.dispatchEvent("animationstart");this.stop()};T.prototype.stop=function(){this.dispatchEvent("animationend")};var mc=function(a,b,c){T.call(this,a,b,c)};s(mc,T);mc.prototype.pa=function(){this.t.style.opacity=0;""!=this.m.style.zIndex&&(this.t.style.zIndex=this.m.style.zIndex+1)};mc.prototype.va=function(){mc.a.va.call(this);this.m.style.opacity=1};mc.prototype.start=function(){this.dispatchEvent("animationstart");var a=new kc,b=nc(this,this.t),c=nc(this,this.m,!0),b=new S(b),c=new S(c);a.add(b);a.add(c);this.n.k(a,"animationend",this.stop);a.start()};
var nc=function(a,b,c){var d=new lc;d.propertyName="opacity";c?(d.K="1",d.J="0"):(d.K="0",d.J="1");d.duration=a.duration+"ms";d.easing=a.easing;d.setElement(b);return d};var oc=function(a,b,c){T.call(this,a,b,c)};s(oc,T);oc.prototype.pa=function(){""!=this.m.style.zIndex&&(this.t.style.zIndex=this.m.style.zIndex+1);this.t.style.display="none"};
oc.prototype.start=function(){this.dispatchEvent("animationstart");var a=window.getComputedStyle(this.m,null).getPropertyValue("width"),b=window.getComputedStyle(this.m,null).getPropertyValue("height"),c=window.getComputedStyle(this.t,null).getPropertyValue("width"),d=window.getComputedStyle(this.t,null).getPropertyValue("height"),f="",g="";switch(this.direction){case "top":f="0px,-"+d;g="0px,"+d;break;case "bottom":f="0px,"+b;g="0px,-"+b;break;case "left":f="-"+c+",0px";g=c+",0px";break;default:f=
a+",0px",g="-"+a+",0px"}a=new kc;b=pc(this,this.t);b.K=f;f=new S(b);a.add(f);"push"==this.type&&(f=pc(this,this.m),f.J=g,g=new S(f),a.add(g));this.n.k(a,"animationend",this.stop);a.start();this.t.style.display="block"};var pc=function(a,b){var c=new lc;c.propertyName="translate";c.K="0px,0px";c.J="0px,0px";c.duration=a.duration+"ms";c.easing=a.easing;c.setElement(b);return c};var qc=function(a,b,c){I.call(this);this.e=a;this.j=b;this.h=c;this.wb=this.h.type||"none";this.d=new N(this)};s(qc,I);e=qc.prototype;e.start=function(){this.dispatchEvent("animationstart");this.e==this.j?this.dispatchEvent("animationend"):this.e&&this.e.isVisible()?(this.d.k(this.e,"hidden",q(this.Ta,this,q(this.Ua,this))),this.e.dismiss()):this.Ta(q(this.Ua,this))};e.Ta=function(a){this.j.isLoaded()?a():(this.d.k(this.j,"load",a),this.j.load())};
e.Ua=function(){var a;a=null;var b=this.j.getElement();this.e&&(a=this.e.getElement());switch(this.wb){case "fade":a=new mc(a,b,this.h);break;case "slide":case "push":a=new oc(a,b,this.h);break;default:a=new T(a,b,this.h)}a.pa();this.j.bind();this.d.k(a,"animationend",this.xb);a.start()};e.xb=function(a){a=a.target;this.e&&this.e.isBound()&&this.e.unbind();a.va();a.dispose();this.dispatchEvent("animationend")};e.b=function(){this.h=null;this.d.dispose();delete this.d;qc.a.b.call(this)};var rc=function(){I.call(this);ob(k,"devicemotion",this.Va,void 0,this)};s(rc,I);e=rc.prototype;e.Ga=NaN;e.Ha=NaN;e.Ia=NaN;e.xa=NaN;e.ya=NaN;e.za=NaN;e.ca=!1;e.Nb=18;e.Pb=200;e.Wb=1E3;e.b=function(){tb(k,"devicemotion",this.Va,void 0,this);rc.a.b.call(this)};e.Va=function(a){a=a.o.accelerationIncludingGravity;this.xa=a.x;this.ya=a.y;this.za=a.z;this.ca||$b(this.Ob,this.Pb,this);this.ca=!0};
e.Ob=function(){var a=Math.abs(this.xa-this.Ga),b=Math.abs(this.ya-this.Ha),c=Math.abs(this.za-this.Ia);this.Ga=this.xa;this.Ha=this.ya;this.Ia=this.za;a+b+c>this.Nb?sc(this):this.ca=!1};var sc=function(a){a.dispatchEvent("shake");a.fa();$b(function(){this.ca=!1},a.Wb,a)};rc.prototype.fa=function(){this.Ia=this.Ha=this.Ga=NaN};var tc=function(){return k.innerWidth>k.innerHeight?"landscape":"portrait"};var U=function(a){I.call(this);this.Z=a;this.d=new N(this);this.d.l(document,"touchmove",ab)};s(U,I);U.prototype.g=function(){return this.d};U.prototype.getEnvironment=function(){return this.Z};U.prototype.b=function(){this.d.dispose();delete this.d;this.Z.dispose&&this.Z.dispose();delete this.Z;U.a.b.call(this)};var V=function(a){U.call(this,a.environment);this.config=a;this.Y={};this.Eb=a.politeLoad;this.rb=tc()};s(V,U);e=V.prototype;e.e=null;e.j=null;e.s=null;e.sa=!1;e.ra=!1;e.init=function(){this.getEnvironment().onInit(this.cc,this)};e.addEventListener=function(a,b,c,d){V.a.addEventListener.call(this,a,b,c,d);"shake"!=a||this.v||(this.v=new rc,this.g().l(this.v,"shake",this.dispatchEvent))};
e.removeEventListener=function(a,b,c,d){V.a.removeEventListener.call(this,a,b,c,d);"shake"==a&&(b=!!c,a=E(this)?this.da(a,b):this?(c=G(this))?c.da(a,b):[]:[],a&&0!=a.length||!this.v||(this.v.dispose(),this.v=null))};e.La=function(a){var b=a.getConfig();this.Y[b.id]=a;if(b.isDefault||!this.s)this.s=a;(a=a.getElement())&&a.parentNode&&a.parentNode.removeChild(a)};e.fc=function(a){this.s=a};
e.Ka=function(a,b,c,d,f){if(!this.j){this.j=a;var g=this.e,h=this.getEnvironment();b=q(this.Bb,this,g,a,b,c,d,f);if(c=g)c=a.getConfig(),c=!(g.getConfig().expanded||!c.expanded);if(c)(g=uc(a))?(this.j=null,g()):(this.sa=!0,h.onExpand(b,this),h.expand());else{if(c=g)a=a.getConfig(),c=!(!g.getConfig().expanded||a.expanded);c?(this.ra=!0,this.g().D(h,"collapse",this.Ra),h.onCollapse(b,this),h.collapse()):b()}}};
var uc=function(a){(a="landscape"==tc()?a.eb:a.fb)&&-1==String(a).indexOf(".goToPage(")&&(a=null);return a};e=V.prototype;e.Bb=function(a,b,c,d,f,g){d&&a||(c="none",d=0);a=new qc(a,b,{type:c,duration:d,easing:f,direction:g});this.g().k(a,"animationend",this.Qb);a.start()};e.Qb=function(a){a.target.dispose();a=this.getEnvironment();this.sa?(this.sa=!1,this.g().k(a,"collapse",this.Ra),a.expandComplete()):this.ra&&(this.ra=!1,a.collapseComplete());this.e=this.j;this.j=null;this.e.present()};
e.Ra=function(){this.s&&this.Ka(this.s)};e.Ib=function(){var a=tc();this.rb!=a&&(this.rb=a,this.dispatchEvent("landscape"==a?"rotatetolandscape":"rotatetoportrait"))};e.cc=function(){this.g().l(k,["resize","orientationchange"],this.Ib);var a=this.getEnvironment();if(this.Eb)a.onPageLoaded(this.Hb,this);else a.onVisible(this.ib,this)};e.Hb=function(){this.getEnvironment().onVisible(this.ib,this)};e.ib=function(){this.getEnvironment().onHidden(this.Vb,this);if(this.s){var a=uc(this.s);a?a():this.Ka(this.s)}};
e.Vb=function(){this.e&&(this.e.dismiss(),this.e.unbind())};e.b=function(){for(var a in this.Y)this.Y[a].dispose();delete this.Y;this.v&&(this.v.dispose(),this.v=null);this.j=this.s=this.e=null;V.a.b.call(this)};m("rad.ad.RichMedia",V,void 0);V.prototype.addEventListener=V.prototype.addEventListener;V.prototype.removeEventListener=V.prototype.removeEventListener;V.prototype.init=V.prototype.init;V.prototype.dispose=V.prototype.dispose;V.prototype.getEnvironment=V.prototype.getEnvironment;V.prototype.addChild=V.prototype.La;V.prototype.setDefaultPage=V.prototype.fc;V.prototype.goToPage=V.prototype.Ka;var W={Xb:function(){var a=document.createElement("IFRAME");a.id="afma-notify-"+(new Date).getTime();a.style.display="none";return a},U:null,gb:function(a){W.Yb(a)||(W.U||(W.U=W.Xb()),W.U.src=a,W.U.parentNode||document.body.appendChild(W.U))},sendMessage:function(a,b){var c=W.nb(a,b);W.gb(c)},notify_:function(a){window.external.notify(a)},Yb:function(a){return window.external&&"notify"in window.external?(W.notify_(a),!0):!1},nb:function(a,b){var c=b||{};c["google.afma.Notify_dt"]=(new Date).getTime();
var d=["gmsg://mobileads.google.com/"+a],f;for(f in c)Bb(f,c[f],d);d[1]&&(c=d[0],f=c.indexOf("#"),0<=f&&(d.push(c.substr(f)),d[0]=c=c.substr(0,f)),f=c.indexOf("?"),0>f?d[1]="?":f==c.length-1&&(d[1]=void 0));return d.join("")}};var X=function(){I.call(this);this.bb=[];this.P=new Zb(100);Za(this,ha($a,this.P));this.hb=new N(this);Za(this,ha($a,this.hb));this.hb.l(this.P,"tick",this.Aa);this.Gb=W.gb;pa&&(this.cb=!1)};s(X,I);X.getInstance=function(){return X.ub?X.ub:X.ub=new X};e=X.prototype;e.b=function(){X.a.b.call(this)};e.cb=!0;e.dc=function(a,b){if("onshow"==a&&"loading"==document.readyState){var c=q(vc,k,a,b);H(k,"DOMContentLoaded",c)}else this.dispatchEvent(new wc(a,this,b))};
e.ec=function(a,b){var c=W.nb(a,b);this.bb.push(c);this.kb()};e.Aa=function(){var a=this.bb.shift();a?this.Gb(a):this.P.stop()};e.kb=function(){"loading"==document.readyState?H(k,"DOMContentLoaded",this.kb,!1,this):this.cb?this.P.enabled||(this.Aa(),this.P.start()):this.Aa()};var wc=function(a,b,c){D.call(this,a,b);this.params=c};s(wc,D);
if(!(k.AFMA_AddEventListener&&k.AFMA_ReceiveMessage&&k.AFMA_RemoveEventListener&&k.AFMA_SendMessage)){var Y=X.getInstance(),xc=q(Y.addEventListener,Y),yc=q(Y.removeEventListener,Y),zc=q(Y.dc,Y),Ac=q(Y.ec,Y);m("AFMA_AddEventListener",xc,k);m("AFMA_ReceiveMessage",zc,k);m("AFMA_RemoveEventListener",yc,k);m("AFMA_SendMessage",Ac,k)}var Bc=function(a,b){k.AFMA_AddEventListener(a,b,void 0,void 0)},vc=function(a,b){k.AFMA_ReceiveMessage(a,b)},Z={};
m("AFMA_AddObserver",function(a,b,c){var d=q(function(a){c(a.type,a.params)},b);Bc(a,d);Z[a]||(Z[a]={});Z[a][b]=d},void 0);m("AFMA_RemoveObserver",function(a,b){Z[a]&&Z[a][b]&&(k.AFMA_RemoveEventListener(a,Z[a][b],void 0,void 0),delete Z[a][b])},void 0);Bc("onshow",function(){});Bc("onhide",function(){});var Cc=function(a){var b=document.createElement("IMG");b.style.visibility="hidden";b.style.width="0px";b.style.height="0px";b.src=a;b.onload=function(){b.src=""};document.body.appendChild(b)};var Dc=function(){I.call(this);this.u=this.lb=this.ia=!1;this.na={}};s(Dc,I);var Ec=["impurl","impurl3party"],Fc=["clickurl","clickurl3party"];e=Dc.prototype;e.la=function(){var a=q(this.ac,this);"loading"===document.readyState?H(document,"DOMContentLoaded",a):a()};e.ac=function(){this.ia=!0;this.dispatchEvent("init");this.u&&this.X()};e.ma=function(){this.lb=!0;this.dispatchEvent("pageloaded")};e.X=function(){var a=q(this.bc,this);"complete"===document.readyState?a():H(window,"load",a)};
e.bc=function(){this.u=!0;this.ia&&(Gc(this,Ec),this.dispatchEvent("visible"))};e.Oa=function(){this.dispatchEvent("expand")};e.Na=function(){this.dispatchEvent("collapse")};e.Pa=function(){this.onVisible(this.$b,this)};e.$b=function(){this.u=!1;this.dispatchEvent("hidden")};e.onInit=function(a,b){this.isInitialized()?a.call(b):H(this,"init",a,void 0,b)};e.onPageLoaded=function(a,b){this.isPageLoaded()?a.call(b):H(this,"pageloaded",a,void 0,b)};
e.onVisible=function(a,b){this.isVisible()?a.call(b):H(this,"visible",a,void 0,b)};e.onHidden=function(a,b){H(this,"hidden",a,void 0,b)};e.isInitialized=function(){return this.ia};e.isPageLoaded=function(){return this.lb};e.isVisible=function(){return this.ia&&this.u};e.trackProgress=function(a,b){this.trackInteraction();b=25*Math.floor(4*b);0===b?this.incrementCounter(a+" Start"):this.incrementCounter(a+" "+b+"%")};
e.exit=function(a,b,c,d){Gc(this,Fc);if(void 0!==c){if(b=c){c=ka("%","time","%");var f=Math.round(ia()/1E3);b=b.replace(c,f.toString());c=ka("%","pa","%");b=b.replace(c,"0")}c=b}this.c.exit(a,c);d&&this.c.requestCollapse()};var Gc=function(a,b){for(var c=0;c<b.length;c++){var d=b[c];a.na[d]||(a.na[d]=!0,(d=Db(k.location.href,d))&&Cc(d))}};e=Dc.prototype;e.reportManualClose=function(){};e.expand=function(){};e.onExpand=function(){};e.expandComplete=function(){};e.collapse=function(){};
e.onCollapse=function(){};e.collapseComplete=function(){};e.b=function(){delete this.na;if(this)if(E(this))this.removeAllListeners("pageloaded");else{var a=G(this);if(a){var b=0,c;for(c in a.f)if("pageloaded"==c)for(var d=Qa(a.f[c]),f=0;f<d.length;++f)ub(d[f])&&++b}}Dc.a.b.call(this)};var Hc=function(a){Dc.call(this);this.c=a;this.wa=[];this.c.isInitialized()?this.la():this.c.addEventListener(studio.events.StudioEvent.INIT,this.la,void 0,this);this.c.isPageLoaded()?this.ma():this.c.addEventListener(studio.events.StudioEvent.PAGE_LOADED,this.ma,void 0,this);this.c.isVisible()&&this.X();this.c.addEventListener(studio.events.StudioEvent.VISIBLE,this.X,void 0,this);this.c.addEventListener(studio.events.StudioEvent.HIDDEN,this.Pa,void 0,this);this.c.addEventListener(studio.events.StudioEvent.EXPAND_START,
this.Oa,void 0,this);this.c.addEventListener(studio.events.StudioEvent.COLLAPSE_START,this.Na,void 0,this)};s(Hc,Dc);e=Hc.prototype;e.getFilename=function(a){return this.c.getUrl(a)};e.trackBrandingAssetsLoaded=function(){this.incrementCounter("branding")};e.trackAllAssetsLoaded=function(){this.incrementCounter("interactive")};e.incrementCounter=function(a,b){this.c.counter(a,b)};e.trackInteraction=function(){};e.startTimer=function(a){this.c.startTimer(a)};e.stopTimer=function(a){this.c.stopTimer(a)};
e.trackVideo=function(a,b,c){this.wa.push({id:a,Kb:b,Jb:c});this.c.loadModule(studio.module.ModuleId.VIDEO,q(this.Lb,this))};e.Lb=function(){for(;this.wa.length;){var a=this.wa.shift();studio.video.Reporter.attach(a.id,a.Kb,a.Jb)}};e.untrackVideo=function(a){studio.video&&studio.video.Reporter&&studio.video.Reporter.detach&&studio.video.Reporter.detach(a)};e.reportManualClose=function(){this.c.reportManualClose()};e.expand=function(){this.c.requestExpand()};
e.onExpand=function(a,b){H(this,"expand",a,void 0,b)};e.expandComplete=function(){this.c.finishExpand()};e.collapse=function(){this.c.requestCollapse()};e.onCollapse=function(a,b){H(this,"collapse",a,void 0,b)};e.collapseComplete=function(){this.c.finishCollapse()};
e.b=function(){this.c.removeEventListener(studio.events.StudioEvent.INIT,this.la,void 0,this);this.c.removeEventListener(studio.events.StudioEvent.PAGE_LOADED,this.ma,void 0,this);this.c.removeEventListener(studio.events.StudioEvent.VISIBLE,this.X,void 0,this);this.c.removeEventListener(studio.events.StudioEvent.HIDDEN,this.Pa,void 0,this);this.c.removeEventListener(studio.events.StudioEvent.EXPAND_START,this.Oa,void 0,this);this.c.removeEventListener(studio.events.StudioEvent.COLLAPSE_START,this.Na,
void 0,this);Hc.a.b.call(this)};var Ic=function(){Hc.call(this,Enabler)};s(Ic,Hc);m("rad.environment.DoubleClickStudio",Ic,void 0);var $=Ic.prototype;$.addEventListener=$.addEventListener;$.removeEventListener=$.removeEventListener;$.onInit=$.onInit;$.onVisible=$.onVisible;$.onHidden=$.onHidden;$.isInitialized=$.isInitialized;$.isVisible=$.isVisible;$.getFilename=$.getFilename;$.trackBrandingAssetsLoaded=$.trackBrandingAssetsLoaded;$.trackAllAssetsLoaded=$.trackAllAssetsLoaded;$.incrementCounter=$.incrementCounter;$.trackInteraction=$.trackInteraction;$.trackProgress=$.trackProgress;
$.startTimer=$.startTimer;$.stopTimer=$.stopTimer;$.trackVideo=$.trackVideo;$.untrackVideo=$.untrackVideo;$.exit=$.exit;$.setParentEventTarget=$.gc;$.reportManualClose=$.reportManualClose;})();
</script><script type="text/javascript" data-exports-type="rad.ui.GallerySwipable">// Copyright 2013 Google Inc. All Rights Reserved.
(function(){var f,k=this,l=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},m=function(a){return"array"==l(a)},aa=function(a){var b=l(a);return"array"==b||"object"==b&&"number"==typeof a.length},p=function(a){return"string"==typeof a},ba=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ca="closure_uid_"+(1E9*Math.random()>>>0),da=0,ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,
2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return q.apply(null,arguments)},ga=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ha=function(a,b){var c=a.split("."),d=k;
c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b},r=function(a,b){function c(){}c.prototype=b.prototype;a.c=b.prototype;a.prototype=new c};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return q.apply(null,c)}return q(this,a)};var ia=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)},ja="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),s=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<ja.length;g++)c=ja[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var ka;var qa=function(a){if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pa,"&quot;"));return a},ma=/&/g,na=/</g,oa=/>/g,pa=/\"/g,la=/[&<>\"]/,ra=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})},sa=function(a){var b=p(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+
(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};var t=Array.prototype,ta=t.indexOf?function(a,b,c){return t.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=t.forEach?function(a,b,c){t.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=p(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},wa=function(a,b){var c=ta(a,b),d;(d=0<=c)&&t.splice.call(a,c,1);return d},xa=function(a){var b=a.length;if(0<
b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},ya=function(a,b,c){return 2>=arguments.length?t.slice.call(a,b):t.slice.call(a,b,c)};var u,za,Aa,Ba,Ca=function(){return k.navigator?k.navigator.userAgent:null};Ba=Aa=za=u=!1;var v;if(v=Ca()){var Da=k.navigator;u=0==v.lastIndexOf("Opera",0);za=!u&&(-1!=v.indexOf("MSIE")||-1!=v.indexOf("Trident"));Aa=!u&&-1!=v.indexOf("WebKit");Ba=!u&&!Aa&&!za&&"Gecko"==Da.product}var Ea=u,w=za,x=Ba,A=Aa,Fa=function(){var a=k.document;return a?a.documentMode:void 0},Ga;
t:{var Ha="",B;if(Ea&&k.opera)var Ia=k.opera.version,Ha="function"==typeof Ia?Ia():Ia;else if(x?B=/rv\:([^\);]+)(\)|;)/:w?B=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:A&&(B=/WebKit\/(\S+)/),B)var Ja=B.exec(Ca()),Ha=Ja?Ja[1]:"";if(w){var Ka=Fa();if(Ka>parseFloat(Ha)){Ga=String(Ka);break t}}Ga=Ha}
var La=Ga,Ma={},C=function(a){var b;if(!(b=Ma[a])){b=0;for(var c=String(La).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",n=d[g]||"",ua=RegExp("(\\d*)(\\D*)","g"),Gb=RegExp("(\\d*)(\\D*)","g");do{var y=ua.exec(h)||["","",""],z=Gb.exec(n)||["","",""];if(0==y[0].length&&0==z[0].length)break;b=((0==y[1].length?0:parseInt(y[1],10))<(0==z[1].length?0:parseInt(z[1],10))?-1:(0==y[1].length?
0:parseInt(y[1],10))>(0==z[1].length?0:parseInt(z[1],10))?1:0)||((0==y[2].length)<(0==z[2].length)?-1:(0==y[2].length)>(0==z[2].length)?1:0)||(y[2]<z[2]?-1:y[2]>z[2]?1:0)}while(0==b)}b=Ma[a]=0<=b}return b},Na=k.document,Oa=Na&&w?Fa()||("CSS1Compat"==Na.compatMode?parseInt(La,10):5):void 0;var Pa=!w||w&&9<=Oa;!x&&!w||w&&w&&9<=Oa||x&&C("1.9.1");w&&C("9");var Qa=function(a,b){var c;c=a.className;c=p(c)&&c.match(/\S+/g)||[];for(var d=ya(arguments,1),e=c.length+d.length,g=c,h=0;h<d.length;h++)0<=ta(g,d[h])||g.push(d[h]);g=c.join(" ");a.className=g;return c.length==e};var Sa=function(a,b){ia(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Ra?a.setAttribute(Ra[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Ra={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ua=function(a,b,c){return Ta(document,arguments)},
Ta=function(a,b){var c=b[0],d=b[1];if(!Pa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',qa(d.name),'"');if(d.type){c.push(' type="',qa(d.type),'"');var e={};s(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(p(d)?c.className=d:m(d)?Qa.apply(null,[c].concat(d)):Sa(c,d));2<b.length&&Va(a,c,b);return c},Va=function(a,b,c){function d(c){c&&b.appendChild(p(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var g=c[e];!aa(g)||ba(g)&&0<g.nodeType?d(g):va(Wa(g)?xa(g):
g,d)}},Xa=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},Wa=function(a){if(a&&"number"==typeof a.length){if(ba(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==l(a))return"function"==typeof a.item}return!1},Ya=function(a){this.H=a||k.document||document};f=Ya.prototype;f.getElement=function(a){return p(a)?this.H.getElementById(a):a};f.createDom=function(a,b,c){return Ta(this.H,arguments)};f.createElement=function(a){return this.H.createElement(a)};
f.createTextNode=function(a){return this.H.createTextNode(String(a))};f.appendChild=function(a,b){a.appendChild(b)};var Za=function(a){Za[" "](a);return a};Za[" "]=function(){};var $a=!w||w&&9<=Oa,ab=w&&!C("9");!A||C("528");x&&C("1.9b")||w&&C("8")||Ea&&C("9.5")||A&&C("528");x&&!C("8")||w&&C("9");var D=function(){};D.prototype.ba=!1;D.prototype.isDisposed=function(){return this.ba};D.prototype.dispose=function(){this.ba||(this.ba=!0,this.h())};D.prototype.h=function(){if(this.ta)for(;this.ta.length;)this.ta.shift()()};var E=function(a,b){this.type=a;this.currentTarget=this.target=b};f=E.prototype;f.h=function(){};f.dispose=function(){};f.s=!1;f.defaultPrevented=!1;f.ka=!0;f.stopPropagation=function(){this.s=!0};f.preventDefault=function(){this.defaultPrevented=!0;this.ka=!1};var F=function(a,b){a&&this.init(a,b)};r(F,E);f=F.prototype;f.target=null;f.relatedTarget=null;f.offsetX=0;f.offsetY=0;f.clientX=0;f.clientY=0;f.screenX=0;f.screenY=0;f.button=0;f.keyCode=0;f.charCode=0;f.ctrlKey=!1;f.altKey=!1;f.shiftKey=!1;f.metaKey=!1;f.b=null;
f.init=function(a,b){var c=this.type=a.type;E.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(x){var e;t:{try{Za(d.nodeName);e=!0;break t}catch(g){}e=!1}e||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=A||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=A||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.b=a;a.defaultPrevented&&this.preventDefault();delete this.s};f.stopPropagation=function(){F.c.stopPropagation.call(this);this.b.stopPropagation?this.b.stopPropagation():this.b.cancelBubble=!0};
f.preventDefault=function(){F.c.preventDefault.call(this);var a=this.b;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};f.h=function(){};var bb="closure_listenable_"+(1E6*Math.random()|0),G=function(a){try{return!(!a||!a[bb])}catch(b){return!1}},cb=0;var db=function(a,b,c,d,e){this.v=a;this.U=null;this.src=b;this.type=c;this.capture=!!d;this.R=e;this.key=++cb;this.B=this.Q=!1},eb=function(a){a.B=!0;a.v=null;a.U=null;a.src=null;a.R=null};var H=function(a){this.src=a;this.g={};this.G=0};H.prototype.add=function(a,b,c,d,e){var g=this.g[a];g||(g=this.g[a]=[],this.G++);var h=fb(g,b,d,e);-1<h?(a=g[h],c||(a.Q=!1)):(a=new db(b,this.src,a,!!d,e),a.Q=c,g.push(a));return a};H.prototype.remove=function(a,b,c,d){if(!(a in this.g))return!1;var e=this.g[a];b=fb(e,b,c,d);return-1<b?(eb(e[b]),t.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.G--),!0):!1};
var gb=function(a,b){var c=b.type;if(!(c in a.g))return!1;var d=wa(a.g[c],b);d&&(eb(b),0==a.g[c].length&&(delete a.g[c],a.G--));return d};H.prototype.removeAll=function(a){var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,eb(d[e]);delete this.g[c];this.G--}return b};H.prototype.I=function(a,b,c,d){a=this.g[a];var e=-1;a&&(e=fb(a,b,c,d));return-1<e?a[e]:null};var fb=function(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.B&&g.v==b&&g.capture==!!c&&g.R==d)return e}return-1};var hb="closure_lm_"+(1E6*Math.random()|0),I={},ib=0,jb=function(a,b,c,d,e){if(m(b)){for(var g=0;g<b.length;g++)jb(a,b[g],c,d,e);return null}c=kb(c);return G(a)?a.r(b,c,d,e):lb(a,b,c,!1,d,e)},lb=function(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=!!e,n=J(a);n||(a[hb]=n=new H(a));c=n.add(b,c,d,e,g);if(c.U)return c;d=mb();c.U=d;d.src=a;d.v=c;a.addEventListener?a.addEventListener(b,d,h):a.attachEvent(b in I?I[b]:I[b]="on"+b,d);ib++;return c},mb=function(){var a=nb,b=$a?function(c){return a.call(b.src,
b.v,c)}:function(c){c=a.call(b.src,b.v,c);if(!c)return c};return b},ob=function(a,b,c,d,e){if(m(b)){for(var g=0;g<b.length;g++)ob(a,b[g],c,d,e);return null}c=kb(c);return G(a)?a.T(b,c,d,e):lb(a,b,c,!0,d,e)},pb=function(a,b,c,d,e){if(m(b))for(var g=0;g<b.length;g++)pb(a,b[g],c,d,e);else c=kb(c),G(a)?a.aa(b,c,d,e):a&&(a=J(a))&&(b=a.I(b,c,!!d,e))&&qb(b)},qb=function(a){if("number"==typeof a||!a||a.B)return!1;var b=a.src;if(G(b))return gb(b.l,a);var c=a.type,d=a.U;b.removeEventListener?b.removeEventListener(c,
d,a.capture):b.detachEvent&&b.detachEvent(c in I?I[c]:I[c]="on"+c,d);ib--;(c=J(b))?(gb(c,a),0==c.G&&(c.src=null,b[hb]=null)):eb(a);return!0},sb=function(a,b,c,d){var e=1;if(a=J(a))if(b=a.g[b])for(b=xa(b),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.B&&(e&=!1!==rb(g,d))}return Boolean(e)},rb=function(a,b){var c=a.v,d=a.R||a.src;a.Q&&qb(a);return c.call(d,b)},nb=function(a,b){if(a.B)return!0;if(!$a){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=
null;break t}c=d}e=c;c=new F(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var g=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){g=!0}if(g||void 0==e.returnValue)e.returnValue=!0}e=[];for(g=c.currentTarget;g;g=g.parentNode)e.push(g);for(var g=a.type,n=e.length-1;!c.s&&0<=n;n--)c.currentTarget=e[n],d&=sb(e[n],g,!0,c);for(n=0;!c.s&&n<e.length;n++)c.currentTarget=e[n],d&=sb(e[n],g,!1,c)}return d}return rb(a,new F(b,this))},J=function(a){a=a[hb];return a instanceof H?a:null},tb="__closure_events_fn_"+
(1E9*Math.random()>>>0),kb=function(a){return"function"==l(a)?a:a[tb]||(a[tb]=function(b){return a.handleEvent(b)})};var K=window.location.href,ub=K.search(/#|$/),L;i:{for(var M=0;0<=(M=K.indexOf("canvasLogLevel",M))&&M<ub;){var vb=K.charCodeAt(M-1);if(38==vb||63==vb){var wb=K.charCodeAt(M+14);if(!wb||61==wb||38==wb||35==wb){L=M;break i}}M+=15}L=-1}if(!(0>L)){var xb=K.indexOf("&",L);if(0>xb||xb>ub)xb=ub;L+=15;K.substr(L,xb-L).replace(/\+/g," ")};var N=function(){this.l=new H(this);this.za=this};r(N,D);N.prototype[bb]=!0;f=N.prototype;f.V=null;f.S=function(a){this.V=a};f.addEventListener=function(a,b,c,d){jb(this,a,b,c,d)};f.removeEventListener=function(a,b,c,d){pb(this,a,b,c,d)};
f.dispatchEvent=function(a){var b,c=this.V;if(c)for(b=[];c;c=c.V)b.push(c);var c=this.za,d=a.type||a;if(p(a))a=new E(a,c);else if(a instanceof E)a.target=a.target||c;else{var e=a;a=new E(d,c);s(a,e)}var e=!0,g;if(b)for(var h=b.length-1;!a.s&&0<=h;h--)g=a.currentTarget=b[h],e=yb(g,d,!0,a)&&e;a.s||(g=a.currentTarget=c,e=yb(g,d,!0,a)&&e,a.s||(e=yb(g,d,!1,a)&&e));if(b)for(h=0;!a.s&&h<b.length;h++)g=a.currentTarget=b[h],e=yb(g,d,!1,a)&&e;return e};
f.h=function(){N.c.h.call(this);this.removeAllListeners();this.V=null};f.r=function(a,b,c,d){return this.l.add(String(a),b,!1,c,d)};f.T=function(a,b,c,d){return this.l.add(String(a),b,!0,c,d)};f.aa=function(a,b,c,d){return this.l.remove(String(a),b,c,d)};f.removeAllListeners=function(a){return this.l?this.l.removeAll(a):0};
var yb=function(a,b,c,d){b=a.l.g[String(b)];if(!b)return!0;b=xa(b);for(var e=!0,g=0;g<b.length;++g){var h=b[g];if(h&&!h.B&&h.capture==c){var n=h.v,ua=h.R||h.src;h.Q&&gb(a.l,h);e=!1!==n.call(ua,d)&&e}}return e&&!1!=d.ka};N.prototype.I=function(a,b,c,d){return this.l.I(String(a),b,c,d)};var O=function(){N.call(this);this.K=[];this.pa=0};r(O,N);var zb=["abort","error","load"];O.prototype.add=function(a){if("string"==typeof a)this.K.push(a);else for(var b in a)this.K.push(a[b])};O.prototype.start=function(){Ab(this);for(var a in this.K){var b=this.K[a],c=document.createElement("img");ob(c,zb,this.Aa,void 0,this);c.src=b}};O.prototype.Aa=function(){this.pa++;this.dispatchEvent("progress");Ab(this)};var Ab=function(a){a.pa==a.K.length&&a.dispatchEvent("complete")};var Bb=function(){O.call(this)};r(Bb,O);var Db=function(a,b){p(b)?Cb(a,void 0,b):ia(b,ga(Cb,a))},Cb=function(a,b,c){var d;t:if(d=ra(c),void 0===a.style[d]&&(c=(A?"Webkit":x?"Moz":w?"ms":Ea?"O":null)+sa(c),void 0!==a.style[c])){d=c;break t}d&&(a.style[d]=b)};var P=function(a){this.m=a;this.J={}};r(P,D);var Eb=[];f=P.prototype;f.r=function(a,b,c,d,e){m(b)||(Eb[0]=b,b=Eb);for(var g=0;g<b.length;g++){var h=jb(a,b[g],c||this.handleEvent,d||!1,e||this.m||this);if(!h)break;this.J[h.key]=h}return this};f.T=function(a,b,c,d,e){t:{if(m(b))for(var g=0;g<b.length;g++)this.T(a,b[g],c,d,e);else{a=ob(a,b,c||this.handleEvent,d,e||this.m||this);if(!a){a=this;break t}this.J[a.key]=a}a=this}return a};
f.aa=function(a,b,c,d,e){if(m(b))for(var g=0;g<b.length;g++)this.aa(a,b[g],c,d,e);else c=c||this.handleEvent,e=e||this.m||this,c=kb(c),d=!!d,b=G(a)?a.I(b,c,d,e):a?(a=J(a))?a.I(b,c,d,e):null:null,b&&(qb(b),delete this.J[b.key]);return this};f.removeAll=function(){ia(this.J,qb);this.J={}};f.h=function(){P.c.h.call(this);this.removeAll()};f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Q=function(){};Q.getInstance=function(){return Q.qa?Q.qa:Q.qa=new Q};Q.prototype.xa=0;Q.getInstance();var R=function(a){N.call(this);a||(a=ka||(ka=new Ya));this.la=a};r(R,N);f=R.prototype;f.wa=Q.getInstance();f.C=null;f.o=!1;f.f=null;f.i=null;f.N=null;f.p=null;f.va=!1;f.getElement=function(){return this.f};f.q=function(){return this.A||(this.A=new P(this))};f.ma=function(a){if(this==a)throw Error("Unable to set parent component");if(a&&this.i&&this.C&&this.i.p&&this.C&&this.C in this.i.p&&this.i.p[this.C]&&this.i!=a)throw Error("Unable to set parent component");this.i=a;R.c.S.call(this,a)};
f.S=function(a){if(this.i&&this.i!=a)throw Error("Method not supported");R.c.S.call(this,a)};f.createDom=function(){this.f=this.la.createElement("div")};f.Z=function(a){if(this.o)throw Error("Component already rendered");this.f||this.createDom();a?a.insertBefore(this.f,null):this.la.H.body.appendChild(this.f);this.i&&!this.i.o||Fb(this)};var Fb=function(a){a.o=!0;Hb(a,function(a){!a.o&&a.getElement()&&Fb(a)})},Ib=function(a){Hb(a,function(a){a.o&&Ib(a)});a.A&&a.A.removeAll();a.o=!1};
R.prototype.h=function(){this.o&&Ib(this);this.A&&(this.A.dispose(),delete this.A);Hb(this,function(a){a.dispose()});!this.va&&this.f&&Xa(this.f);this.i=this.f=this.p=this.N=null;R.c.h.call(this)};var Hb=function(a,b){a.N&&va(a.N,b,void 0)};
R.prototype.removeChild=function(a,b){if(a){var c=p(a)?a:a.C||(a.C=":"+(a.wa.xa++).toString(36));a=this.p&&c?(c in this.p?this.p[c]:void 0)||null:null;if(c&&a){var d=this.p;c in d&&delete d[c];wa(this.N,a);b&&(Ib(a),a.f&&Xa(a.f));a.ma(null)}}if(!a)throw Error("Child is not in parent component");return a};var S=function(a){R.call(this);this.na=a};r(S,R);ha("rad.ui.Panel",S);S.prototype.render=S.prototype.Z;S.prototype.dispose=S.prototype.dispose;S.prototype.getElement=S.prototype.getElement;S.prototype.createDom=function(){var a=Ua("DIV"),b=this.na;b&&(p(b)?a.className=b:ba(b)&&Db(a,b));this.f=a};var T=function(a,b){S.call(this,b);this.oa=a};r(T,S);ha("rad.ui.ImagePanel",T);T.prototype.render=T.prototype.Z;T.prototype.dispose=T.prototype.dispose;T.prototype.getElement=T.prototype.getElement;T.prototype.createDom=function(){var a=Ua("IMG",{src:this.oa}),b=this.na;b&&(p(b)?a.className=b:ba(b)&&Db(a,b));this.f=a};T.prototype.ga=function(){return this.oa};T.prototype.getSrc=T.prototype.ga;var U=function(a,b){N.call(this);this.D=a;this.D.id||(this.D.id=(this[ca]||(this[ca]=++da)).toString());this.O=b};r(U,N);f=U.prototype;f.P=!1;f.sa=!1;f.ca=!1;f.getConfig=function(){var a=this.D,b={},c;for(c in a)b[c]=a[c];return b};f.setConfig=function(a){s(this.D,a);this.F()};f.incrementMetricCounter=function(a,b){this.O.getEnvironment().incrementCounter((this.D.name||this.D.id)+" - "+a,b)};f.getElement=function(){return this.f};f.setElement=function(a){this.f=a;this.F()};
f.F=function(){this.getElement();this.getConfig();this.dispatchEvent("configured")};f.q=function(){this.m||(this.m=new P(this));return this.m};var Jb=function(a){a.sa=!0;a.dispatchEvent("load")};f=U.prototype;f.isLoaded=function(){return this.sa};f.isBound=function(){return this.P};f.isVisible=function(){return this.ca};f.ma=function(a){this.i=a;this.S(a)};f.load=function(){this.ra()};f.ra=function(){Jb(this)};f.createDom=function(){var a=document.createElement("DIV");this.setElement(a)};
f.bind=function(){this.P=!0};f.present=function(){this.setVisible()};f.setVisible=function(){this.ca=!0;this.dispatchEvent("visible")};f.dismiss=function(){this.ca=!1;this.dispatchEvent("hidden")};f.unbind=function(){this.m&&(this.m.dispose(),this.m=null);this.P=!1};f.h=function(){this.P&&this.unbind();this.i=null;delete this.f;U.c.h.call(this)};var Kb=function(a,b){if("function"==l(a))b&&(a=q(a,b));else if(a&&"function"==typeof a.handleEvent)a=q(a.handleEvent,a);else throw Error("Invalid listener argument");k.setTimeout(a,0)};var V=function(a,b){U.call(this,a,b);this.a=[];this.k=this.j=null;this.d=this.getConfig().startFrame-1;this.L={pageX:0,w:0,time:null,n:0,t:0,W:!1,X:!1};this.ea=this.fa=!1;this.Y={};this.e=this.getConfig();this.da=!0};r(V,U);
V.prototype.$=function(){return{images:[],width:300,height:200,frameWidth:160,frameHeight:80,borderRadius:1,showNeighbors:!0,neighborRotationY:38,neighborTranslationX:20,neighborTranslationY:-8,neighborTranslationZ:-80,transitionThreshold:70,outOfBoundsResistance:2,showReflection:!1,transitionDuration:600,playIntroAnimation:!1,startFrame:2,frameVeriticalOffset:8}};V.prototype.M="ontouchstart"in window;V.prototype.u=0;V.prototype.Ba=function(a,b){Lb(this,a-1,b)};
var Lb=function(a,b,c){var d=a.e,e=a.a;if(0!=e.length){if(0>b||b>=e.length)b=0;s(a.j.style,void 0!==c&&!1==c?W(0):W(d.transitionDuration));a.u=-b*d.frameWidth;d.showNeighbors&&(a.u+=(d.width-d.frameWidth)/2);s(a.j.style,Mb(a.u,0,0));var g=c=null;0==b?g=e[b+1]:b==e.length-1?c=e[b-1]:(c=e[b-1],g=e[b+1]);Nb(a,e[b],0);c&&Nb(a,c,1);g&&Nb(a,g,2);0<=b-2&&Nb(a,e[b-2],1);b+2<=e.length-1&&Nb(a,e[b+2],2);a.d=b;a.Y[b]=!0;if(b=!a.ea){b=a.Y;var e=0,h;for(h in b)e++;b=e==d.images.length}b&&(a.ea=!0,a.dispatchEvent("allframesviewed"),
a.incrementMetricCounter("All Frames Viewed"))}},Nb=function(a,b,c){a=a.e;b=b.getElement();switch(c){case 0:X(b,0,0,0,0,a.transitionDuration);break;case 1:X(b,a.neighborRotationY,a.neighborTranslationX,a.neighborTranslationY,a.neighborTranslationZ,a.transitionDuration);break;case 2:X(b,-a.neighborRotationY,-a.neighborTranslationX,a.neighborTranslationY,a.neighborTranslationZ,a.transitionDuration)}},X=function(a,b,c,d,e,g){s(a.style,W(g));s(a.style,Mb(c,d,e,b))},Qb=function(a,b){var c=a.e,d=a.O.getEnvironment(),
e={"float":"left","border-radius":c.borderRadius+"px",width:c.frameWidth+"px",height:c.frameHeight+"px"};c.showReflection&&s(e,Ob("below 0px -webkit-gradient(linear, left top, left bottom, from(transparent), color-stop(50%, transparent), to(rgba(255,255,255,0.2)))"));s(e,{"user-select":"none","-moz-user-select":"none","-ms-user-select":"none","-webkit-user-select":"none"});c=new T(d.getFilename(b),e);c.isDisposed()||c.o||(a.a.push(c),Pb(a),c.Z(a.j))},Pb=function(a){var b=a.e;null!=a.j&&(a.j.style.width=
b.frameWidth*a.a.length+"px")};V.prototype.ja=function(a){if(0!=this.a.length){this.M||a.preventDefault();var b=this.L;b.W=!0;this.M?(b.pageX=a.b.touches[0].pageX,b.w=a.b.touches[0].pageX):(b.pageX=a.b.pageX,b.w=a.b.pageX);b.time=Date.now();b.n=0}};
V.prototype.ia=function(a){var b=this.e;if(0!=this.a.length){var c=this.L;if(this.M){a.preventDefault();if(1<a.b.touches.length||a.b.scale&&1!==a.b.scale)return;c.t=a.b.touches[0].pageX-c.pageX;c.n=a.b.touches[0].pageX-c.w;c.w=a.b.touches[0].pageX}else{if(!c.W)return;c.t=a.b.pageX-c.pageX;c.n=a.b.pageX-c.w;c.w=a.b.pageX}c.X=!0;var d=this.a[this.d].getElement();this.ua=0>c.t?0:1;a=Math.abs(c.t/b.frameWidth);var e=!1;0==this.ua?(X(d,b.neighborRotationY*a,b.neighborTranslationX*a,b.neighborTranslationY*
a,b.neighborTranslationZ*a,0),this.d!=this.a.length-1?(d=this.a[this.d+1].getElement(),X(d,-b.neighborRotationY*(1-a),-b.neighborTranslationX*(1-a),b.neighborTranslationY*(1-a),b.neighborTranslationZ*(1-a),0)):e=!0):(X(d,b.neighborRotationY*-a,b.neighborTranslationX*-a,b.neighborTranslationY*a,b.neighborTranslationZ*a,0),0!=this.d?(d=this.a[this.d-1].getElement(),X(d,b.neighborRotationY*(1-a),b.neighborTranslationX*(1-a),b.neighborTranslationY*(1-a),b.neighborTranslationZ*(1-a),0)):e=!0);e&&(c.n/=
Math.abs(c.n)/b.frameWidth+b.outOfBoundsResistance);this.u+=c.n;s(this.j.style,W(0));s(this.j.style,Mb(this.u,0,0))}};
V.prototype.ha=function(){var a=this.e;if(0!=this.a.length){var b=this.L;b.W=!1;0==b.n&&250>Date.now()-b.time&&(this.dispatchEvent("PANELTAP"),this.dispatchEvent("PANELTAP-"+this.d));if(b.X){if(a=Math.abs(b.t)>a.transitionThreshold)0>b.t?this.d==this.a.length-1?this.dispatchEvent("reachrightend"):this.d+=1:0<b.t&&(0==this.d?this.dispatchEvent("reachleftend"):this.d-=1);Lb(this,this.d,!0);a&&!this.fa&&(this.dispatchEvent("firstinteraction"),this.incrementMetricCounter("Gallery Swiped"),this.fa=!0);
b.X=!1}}};var Sb=function(a){var b=a.e;if(a.k){var c={position:"absolute",overflow:"hidden",display:"none"};s(c,{perspective:"1000px","-moz-perspective":"1000px","-webkit-perspective":"1000px"});b.playIntroAnimation&&(s(c,Rb(0.75)),s(c,W(1200)));Db(a.k,c)}};f=V.prototype;
f.setElement=function(a){V.c.setElement.call(this,a);this.k=a;Sb(this);a=this.e;this.j=Ua("DIV",{id:"gallery3d-content-strip"});a={position:"absolute",top:a.frameVeriticalOffset+"px"};s(a,{"transform-style":"preserve-3d","-moz-transform-style":"preserve-3d","-webkit-transform-style":"preserve-3d"});Db(this.j,a);this.k.appendChild(this.j)};f.ya=function(){Jb(this);this.O.getEnvironment().trackAllAssetsLoaded()};
f.ra=function(){var a=this.e.images;if(a){for(var b=new Bb,c=this.O.getEnvironment(),d=0;d<a.length;d++)b.add(c.getFilename(a[d]));this.q().T(b,"complete",this.ya);b.start()}else Jb(this)};
f.bind=function(){var a=this.getElement();this.e=this.getConfig();if(this.da){this.da=!1;for(var b=this.e.images,c=0;c<b.length;c++)Qb(this,b[c]);this.F()}this.M?(this.q().r(a,"touchstart",this.ja),this.q().r(a,"touchmove",this.ia),this.q().r(a,"touchend",this.ha)):(this.q().r(a,"mousedown",this.ja),this.q().r(window,"mousemove",this.ia),this.q().r(window,"mouseup",this.ha));V.c.bind.call(this)};
f.present=function(){this.dispatchEvent("allframesloaded");var a=this.e;if(!this.isVisible()&&(Lb(this,this.d,!1),this.k.style.display="block",V.c.present.call(this),a.playIntroAnimation)){var b=Rb(1);Kb(function(){s(this.k.style,b)},this)}};f.dismiss=function(){var a=this.e;this.isVisible()&&(this.k.style.display="none",V.c.dismiss.call(this),a.playIntroAnimation&&s(this.k.style,Rb(0.75)))};
f.h=function(){for(var a=0;a<this.a.length;a++)this.a[a].dispose();this.Y=this.L=this.j=this.a=this.e=null;Xa(this.k);V.c.h.call(this)};f.getConfig=function(){var a=V.c.getConfig.call(this);if(this.k){var b=window.getComputedStyle(this.getElement(),null).getPropertyValue("width").replace("px",""),c=window.getComputedStyle(this.getElement(),null).getPropertyValue("height").replace("px","");a.width||(a.width=parseInt(b,10));a.height||(a.height=parseInt(c,10))}b=this.$();s(b,a);return b};
f.F=function(){V.c.F.call(this);this.e=this.getConfig();if(this.k){Pb(this);Lb(this,this.d);var a=this.getConfig(),b=this.a,c=a.images;if(null!=c&&0!=c.length){var d=!1;if(0==b.length)d=!0;else if(c.length!=b.length)d=!0;else for(var e=0;e<c.length;e++)if(b[e].ga()!=c[e]){d=!0;break}if(d){this.a.length=0;for(a=this.j;b=a.firstChild;)a.removeChild(b);for(b=0;b<c.length;b++)Qb(this,c[b])}else for(b=0;b<this.a.length;b++)d=this.a[b].getElement(),c=a.showReflection?Ob("below 0px -webkit-gradient(linear, left top, left bottom, from(transparent), color-stop(50%, transparent), to(rgba(255,255,255,0.2)))"):
Ob(""),s(d.style,c),d.style.borderRadius=a.borderRadius+"px"}Sb(this)}};
var Mb=function(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return{transform:a,"-moz-transform":a,"-ms-transform":a,"-webkit-transform":a}},W=function(a){a+="ms";return{transition:"transform "+a,"-moz-transition":"-moz-transform "+a,"-webkit-transition":"-webkit-transform "+a}},Ob=function(a){return{"-webkit-box-reflect":a}},Rb=function(a){a="scale3d("+a+", "+a+", "+a+")";return{transform:a,"-moz-transform":a,"-ms-transform":a,"-webkit-transform":a}};var Y=function(a,b){V.call(this,a,b)};r(Y,V);Y.prototype.getConfig=function(){var a=Y.c.getConfig.call(this);a.frameHeight=a.height;a.frameWidth=a.width;return a};Y.prototype.$=function(){var a=Y.c.$.call(this);s(a,{width:200,height:100,showNeighbors:!1,neighborRotationY:0,neighborTranslationX:0,neighborTranslationY:0,neighborTranslationZ:0,frameVeriticalOffset:0,startFrame:1});return a};ha("rad.ui.GallerySwipable",Y);var Z=Y.prototype;Z.addEventListener=Z.addEventListener;Z.removeEventListener=Z.removeEventListener;Z.getElement=Z.getElement;Z.setElement=Z.setElement;Z.getConfig=Z.getConfig;Z.setConfig=Z.setConfig;Z.createDom=Z.createDom;Z.load=Z.load;Z.bind=Z.bind;Z.present=Z.present;Z.dismiss=Z.dismiss;Z.unbind=Z.unbind;Z.dispose=Z.dispose;Z.isDisposed=Z.isDisposed;Z.isLoaded=Z.isLoaded;Z.isBound=Z.isBound;Z.isVisible=Z.isVisible;var $=E.prototype;ha("goog.events.Event",E);
$.stopPropagation=$.stopPropagation;$.preventDefault=$.preventDefault;$.currentTarget=$.currentTarget;$.target=$.target;$.type=$.type;Y.prototype.goToFrame=Y.prototype.Ba;})();
</script>

<!-- テンキー -->
<script type="text/javascript">
<!--
myTotal = 0;  // 現在の合計値
myInput = ""; // 現在入力している値
myCalc = "+"; // 合計と入力値の演算子
myFlg   = 1;  // １回前に入力したもの 0:数字 1:演算子

function myValue(myData){                 // 0～9または小数点ボタンを押した
if (myInput < 1000000000){
  if ((myData==0 || myData==00) && myInput==0){ 
  myInput = "";
  }
  else {
  myFlg = 0;                              // １回前に入力したものは数値
  myInput += myData;                      // 現在入力している値に追加
  document.myForm.myLine.value = myInput; // 現在入力している値表示
  }
  }
  else {
  alert("エラー");
  myInput = 999999999;
  }
}

function myCalculate(myData){               // 演算ボタンを押した
  if (myFlg==0){                            // １回前に入力したものは数値か？
    myFlg = 1;                              // １回前に入力したものは演算子
    myWork = myTotal + myCalc + myInput;    // 一連の計算式を作る
    myTotal = eval(myWork);                 // 計算式を計算させる
    myInput = "";                           // 現在入力している値をクリア
    if (myTotal >= 1000000000){
  alert("エラー");
  myTotal = 999999999;
  }
    document.myForm.myLine.value = myTotal; // 合計を表示
  }
  if (myData == "="){                    // 演算ボタンは[＝]か？
    myTotal = 0;                         // 合計をクリア
    myCalc = "+";                        // 演算子を[+]とする
  }else{                                 // 演算ボタンは[＝]以外である
    myCalc = myData;                     // 演算子を退避させておく
  }
}

function myC(){                           // クリアボタン[C]を押した
  myTotal = 0;                            // 合計クリア
  myCalc = "+";                           // 演算子クリア
  myInput = "";                           // 現在入力している値をクリア
  document.myForm.myLine.value = myTotal; // つまり、０を表示
}



// --></script>

	</head>
	<body>
		<div class="top_container">
		<header>
			<?php echo Asset::img('logo.png', array('height'=>'100%', 'alt'=>'gemky')); ?>
		</header>
		
		<!-- 欲しい商品 -->
		<div class="contents">
			<div class="gwd-page-container">
				<div id="page1" class="gwd-page-wrapper gwd-page-size" data-gwd-component-id="page1">
					<div class="gwd-page-content gwd-page-size">
						<div id="galleryswipable_1" data-gwd-component="rad.ui.GallerySwipable" data-gwd-component-id="galleryswipable_1" class="gwd-div-t831 gwd-gen-ktp6gwdanimation gwd-gen-ktp6gwdanimation-gen-animation0keyframe"></div>
					</div>
				</div>
			</div>
			<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
			
			<!-- テンキー -->
			<div id="tenkey_block">
				<form name="myForm">
					<table border="0" bgcolor="#9932CC">
					<tr>
					<td colspan="2"><input type="text" size="10" name="myLine" class="example" value="0"></td>
					<td class="td1"><input type="button" value=" Ｃ " class="tenKey" onclick="myC()"></td>
					<td class="td1"><input type="button" value=" ÷ " class="tenKey" onclick="myCalculate('/')"></td>
					</tr>
					<tr>
					<td class="td1"><input type="button" value=" ７ " class="tenKey" onclick="myValue(7)"></td>
					<td class="td1"><input type="button" value=" ８ " class="tenKey" onclick="myValue(8)"></td>
					<td class="td1"><input type="button" value=" ９ " class="tenKey" onclick="myValue(9)"></td>
					<td class="td1"><input type="button" value=" × " class="tenKey" onclick="myCalculate('*')"></td>
					</tr>
					<tr>
					<td class="td1"><input type="button" value=" ４ " class="tenKey" onclick="myValue(4)"></td>
					<td class="td1"><input type="button" value=" ５ " class="tenKey" onclick="myValue(5)"></td>
					<td class="td1"><input type="button" value=" ６ " class="tenKey" onclick="myValue(6)"></td>
					<td class="td1"><input type="button" value="-" class="tenKey" onclick="myCalculate('-')"></td>
					</tr>
					<tr>
					<td class="td1"><input type="button" value=" １ " class="tenKey" onclick="myValue(1)"></td>
					<td class="td1"><input type="button" value=" ２ " class="tenKey" onclick="myValue(2)"></td>
					<td class="td1"><input type="button" value=" ３ " class="tenKey" onclick="myValue(3)"></td>
					<td class="td1"><input type="button" value=" + " class="tenKey" onclick="myCalculate('+')"></td>
					</tr>
					<tr>
					<td class="td1"><input type="button" value=" ００ " class="tenKey" onclick="myValue('00')"></td>
					<td class="td1"><input type="button" value=" ０ " class="tenKey" onclick="myValue(0)"></td>
					<td class="td1"><input type="button" value=" 入力 " class="tenKey" onclick="myValue('')"></td>
					<td class="td1"><input type="button" value=" ＝ " class="tenKey" onclick="myCalculate('=')"></td>
					</tr>
					</table>
					</form>
	
			</div>
		</div>
		
		</div>
		<script type="text/nsblock-serialization" data-exports-type="gwd-nsblock">{
 "version": 1,
 "components": {
  "galleryswipable_1": {
   "type": "rad.ui.GallerySwipable",
   "version": 1,
   "properties": {
    "images": {
     "type": "Array.<file>",
     "value": [
      "http://ecx.images-amazon.com/images/I/41oHqcoR%2B5L.jpg",
      "http://ecx.images-amazon.com/images/I/41y81iL7%2BRL._SL500_AA300_.jpg",
      "http://ecx.images-amazon.com/images/I/51MqtMRgcYL._SX395_.jpg",
      "http://ecx.images-amazon.com/images/I/519feFc%2BQKL._SL500_AA300_.jpg",
      "http://ecx.images-amazon.com/images/I/41sVvpIHBBL._SL500_AA300_.jpg"
     ]
    }
   }
  }
 },
 "creativeProperties": {
  "dimensionalOffsets": {
   "left": 0,
   "top": 0
  },
  "dimensions": {
   "minWidth": 300,
   "minHeight": 250,
   "maxWidth": 300,
   "maxHeight": 250
  },
  "startExpanded": false,
  "isMultiDirectional": false
 },
 "exits": {},
 "counters": [
  "amazon_view - All Frames Viewed",
  "amazon_view - Gallery Swiped"
 ],
 "timers": []
}</script><script type="text/javascript" data-exports-type="gwd-generated-code">(function(){var $NSBlockString$=document.querySelector('script[data-exports-type="gwd-nsblock"]').textContent;if(!window.$NSBlock$){window.$NSBlock$=window.JSON.parse($NSBlockString$)}var $NSBlock$=window.$NSBlock$;Enabler.setExpandingPixelOffsets(0,0,300,250,false,false);var initAd=function(){var environment$Config$={isBanner:true,id:"environment"};var environment=new rad.environment.DoubleClickStudio(environment$Config$);var $ad$$Config$={environment:environment,politeLoad:true,id:"$ad$"};var $ad$=new rad.ad.RichMedia($ad$$Config$);var intropage1$Config$={cssClass:"gwd-gen-tofd",elementCount:1,id:"intropage1"};var intropage1=new rad.animation.CSSAnimation(intropage1$Config$,$ad$);var page1$Config$={width:"300px",height:"250px",introAnimationSequence:intropage1,isDefault:true,id:"page1"};var page1=new rad.ui.Page(page1$Config$,$ad$);page1.setElement(document.querySelector('[data-gwd-component-id="page1"]'));var galleryswipable_1$Config$={name:"amazon_view",images:$NSBlock$["components"]["galleryswipable_1"]["properties"]["images"]["value"],startFrame:5,id:"galleryswipable_1"};var galleryswipable_1=new rad.ui.GallerySwipable(galleryswipable_1$Config$,$ad$);galleryswipable_1.setElement(document.querySelector('[data-gwd-component-id="galleryswipable_1"]'));page1.addChild(galleryswipable_1);$ad$.addChild(page1);$ad$.init();document.body.style["display"]="block"};document.body.style["display"]="none";Enabler.isInitialized()&&initAd()||Enabler.addEventListener(studio.events.StudioEvent.INIT,initAd);function StudioExports(){Enabler.counter("amazon_view - All Frames Viewed");Enabler.counter("amazon_view - Gallery Swiped")}})()
</script>
	</body>
</html>
